version: "3.7"
services:
  service1:
    image: dongnguyenvie/public:checkos.node
    ports:
      - 8086:8085
    
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure